### ISSUE TITLE
请问可以用户自助改密码吗  比如管理员在web点击用户更改密码 会发送一个邮件到用户 通过邮件来更改密码

### ISSUE THREAD

**Issue by lixiaokun777** [eryajf/go-ldap-admin#138]
## Question Report

- 搜索打开和关闭的 [GitHub 问题](https://github.com/eryajf/go-ldap-admin/issues)

请在提交问题之前回答这些问题，谢谢。 | Please answer these questions before submitting them. Thank you.

### 问题重现步骤 | Steps to reproduce the problem

**Comment by eryajf** [comment]
您好 @lixiaokun777👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @lixiaokun777. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
查看官方文档，有专门的说明



| |
eryajf
|
|
***@***.***
行者常至，为者常成！
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年12月19日 10:15 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [eryajf/go-ldap-admin] 请问可以用户自助改密码吗  比如管理员在web点击用户更改密码 会发送一个邮件到用户 通过邮件来更改密码 (Issue #138) |

Question Report
搜索打开和关闭的 GitHub 问题

请在提交问题之前回答这些问题，谢谢。 | Please answer these questions before submitting them. Thank you.

你使用了哪个版本？ | Which version did you use?
预期行为 | Expected behavior
实际行为 | Actual behavior
原因分析（如果可以） | Cause analysis (if possible)
问题重现步骤 | Steps to reproduce the problem
