### ISSUE TITLE
最新前后端 登录时提示无权限

### ISSUE THREAD

**Issue by nameGJ** [eryajf/go-ldap-admin#322]
#### 您使用的版本？ | Your usage version?
go-ldap-admin-v0.5.16 +go-ldap-admin-ui-v0.5.15

![743D2F46-13F5-4c15-A92A-17D8B11A3A44](https://github.com/eryajf/go-ldap-admin/assets/85600323/9d94e14f-5615-4cc6-9f2a-cce0cb3d65d9)

**Comment by eryajf** [comment]
您好 @nameGJ👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @nameGJ. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
请给出部署的上下文，只给一个这个，没法判断。建议参照docker-compose部署方案，肯定一遍过。

**Comment by nameGJ** [comment]
我并没有使用docker-compose   而是用的您后端版本发布里的压缩包直接解压运行的 前端我已修改.env.production中的VUE_APP_BASE_API配置项 并且编译部署的

**Comment by eryajf** [comment]
> 我并没有使用docker-compose 而是用的您后端版本发布里的压缩包直接解压运行的 前端我已修改.env.production中的VUE_APP_BASE_API配置项 并且编译部署的

那可以看下mysql里的数据，如果里边没有数据，则需要把sql导入一下。sql在 docs/sql/go_ldap_admin.sql

**Comment by nameGJ** [comment]
已经重新导出数据库
![0A8F3E80-7D09-4f54-9B02-D9ABFF75548C](https://github.com/eryajf/go-ldap-admin/assets/85600323/70c8043b-9c5e-4005-8ad5-32b57de7049f)

**Comment by nameGJ** [comment]
这里是日志
![Uploading 微信图片_20240327113852.png…]()

**Comment by nameGJ** [comment]
![Uploading 微信图片_20240327113852.png…]()

**Comment by nameGJ** [comment]
![20240327113852](https://github.com/eryajf/go-ldap-admin/assets/85600323/a462101b-e8dc-4477-8f0c-c0066215e5b2)
zh这里是日子

**Comment by nameGJ** [comment]
这里是日志
![20240327113852](https://github.com/eryajf/go-ldap-admin/assets/85600323/68c6a933-3780-4faf-8489-e894779dc6dc)

**Comment by Muncan90** [comment]
> The database has been re-exported ![0A8F3E80-7D09-4f54-9B02-D9ABFF75548C](https://private-user-images.githubusercontent.com/85600323/317110308-70c8043b-9c5e-4005-8ad5-32b57de7049f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyNDYxMTMsIm5iZiI6MTcxOTI0NTgxMywicGF0aCI6Ii84NTYwMDMyMy8zMTcxMTAzMDgtNzBjODA0M2ItOWM1ZS00MDA1LThhZDUtMzJiNTdkZTcwNDlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDE2MTY1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwODczOWVjNDMwOTAwZWJlZDZiYzlmM2JlOGYyMzIyYjYyYjU3ZTNhNDFhMjZiNjMwM2UxNzUwZTBlM2ExZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bSyVlLdjU3adufrqnonIU8n2-rq-AJogkIppDJ0SncA)

the 401 error in your screenshot is being served by the middleware\CasbinMiddleware.go file which is functioning correctly

https://github.com/eryajf/go-ldap-admin/blob/d4c7ed5e32e56240231ae6da8c655dc16dc341f7/middleware/CasbinMiddleware.go#L46

the root cause is because the current version of the docs/sql/go_ldap_admin.sql file is missing a required casbin rule.

you can add it to the existing database:

```
INSERT INTO `casbin_rule` (`ptype`, `v0`, `v1`, `v2`, `v3`, `v4`, `v5`)
VALUES ('p', 'admin', '/menu/access/tree', 'GET', '', '', '');
```

then you should be able to login successfully after an application restart


---

您截图中的 401 错误是由正常运行的 middleware\CasbinMiddleware.go 文件提供的。

https://github.com/eryajf/go-ldap-admin/blob/d4c7ed5e32e56240231ae6da8c655dc16dc341f7/middleware/CasbinMiddleware.go#L46

根本原因是当前版本的 docs/sql/goo_ldap_admin.sql 文件缺少一条必要的 casbin 规则。

您可以将其添加到现有数据库中：

```
INSERT INTO `casbin_rule` (`ptype`, `v0`, `v1`, `v2`, `v3`, `v4`, `v5`)
VALUES（'p'、'admin'、'/menu/access/tree'、'GET'、''、''、''）；
```

然后您就可以在应用程序重启后成功登录了
